services:
  leetgo-server:
    image: smcgarril/leetgo-server:latest
    restart: always
    build: ./server
    environment:
      - WORKER_HOST=http://leetgo-worker
      - WORKER_PORT=8081
      - WORKER_PATH=/process-code
    networks:
      - leetgo-network
    ports:
      - "8080:8080"
    depends_on:
      - leetgo-worker

  leetgo-worker:
    image: smcgarril/leetgo-worker:latest
    restart: always
    build: ./worker
    networks:
      - leetgo-network
    ports:
      - "8081:8081"
    pids_limit: 60
    cpus: 1
    mem_limit: 150M

networks:
  leetgo-network:
    driver: bridge


